services:
  redis:
    image: redis
    ports:
    - 6379:6379

  mongo:
    image: mongo
    volumes:
    - mongo_data:/data/db
    ports:
    - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: hearky
      MONGO_INITDB_ROOT_PASSWORD: hearky

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: hearky
      ME_CONFIG_MONGODB_ADMINPASSWORD: hearky

volumes:
  mongo_data: {}